[package]
name = "Pico-test-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object = "0.32.2"
probe-rs = "0.22"
symex = { git = "https://github.com/s7rul/symex", tag = "Thesis_version" }